import Foundation

/// EPÍLOGO POR PALABRAS CLAVE
///
/// La crónica registra 122 palabras clave, pero la mayoría no abre ni cierra
/// ninguna puerta: son memoria, no mecánica. Este fichero las convierte en lo
/// único que necesitaban, consecuencia narrativa. Al llegar a un final, el
/// texto añade las líneas de cierre que te hayas ganado.
///
/// Regla de oro: aquí no hay reglas. Nada de esto se anota en la ficha, nada
/// de esto cambia un número. Si una palabra clave necesitase una tirada,
/// estaría en ReglasEspeciales.swift, no aquí.
///
/// GENERADO desde ceniza-y-corona-app/lib/epilogue.ts. No editar a mano:
/// cambia el TypeScript y ejecuta CenizaYCorona/scripts/gen-epilogo-swift.mjs.
enum Epilogo {
    struct Linea: Hashable, Identifiable {
        var id: String { flag }
        let flag: String
        let texto: String
    }

    /// Cuántas líneas se leen como máximo al cerrar una partida.
    static let maximoDeLineas = 9

    static let lineas: [Linea] = [
        Linea(flag: "PROMESA_A_BREN",
              texto: "Le prometiste a Bren que volverías a por él. Los que cuentan esta historia discuten casi todo menos eso: que cumpliste."),
        Linea(flag: "JURAMENTO_DE_YGRID",
              texto: "El juramento que le hiciste a Sor Ygrid en el patio de El Yunque Frío no aparece en ningún registro de la Orden. Ella lo recuerda entero."),
        Linea(flag: "VISTE_A_BREN_CAUTIVO",
              texto: "Nunca se te fue de la cabeza la imagen de Bren entre dos guardias, mirándote sin pedir ayuda. Es lo que te hizo seguir andando cuando ya no quedaban razones."),
        Linea(flag: "HONDA_DE_BREN",
              texto: "Conservaste la honda hasta el final. Está gastada por el uso y nadie sabría decir de quién fue, pero tú sí."),
        Linea(flag: "MANOS_DE_VALCENAR",
              texto: "En Valcenar todavía se dice \"manos de Valcenar\" cuando alguien arregla algo que no era suyo. Empezaron a decirlo por ti."),
        Linea(flag: "HISTORIA_DEL_PADRE_CENIZA",
              texto: "Escuchaste la historia del Padre Ceniza de su propia boca. Eso no te hizo perdonarlo. Te hizo entenderlo, que es peor."),
        Linea(flag: "LA_VERDAD_DE_TOMAS",
              texto: "Tomás dijo la verdad una sola vez, y te la dijo a ti. Le costó todo lo demás."),
        Linea(flag: "NINOS_ESCONDIDOS",
              texto: "Los niños que escondiste bajo el suelo de la capilla salieron de allí al amanecer. Ninguno de ellos recuerda tu cara; todos recuerdan tu voz diciéndoles que no hicieran ruido."),
        Linea(flag: "PIEDAD_EN_LAS_RUINAS",
              texto: "Tuviste piedad entre las ruinas cuando nadie te miraba y nadie iba a agradecértelo. Es la clase de cosa por la que se mide a la gente."),
        Linea(flag: "SANGRE_INNECESARIA",
              texto: "Hubo sangre que no hacía falta derramar. La derramaste igual. Eso también viaja contigo."),
        Linea(flag: "SENDA_DEL_GUARDIAN",
              texto: "Elegiste la senda del Guardián: quedarte delante, siempre delante, aunque doliera."),
        Linea(flag: "SENDA_DEL_PROTECTOR",
              texto: "Elegiste la senda del Protector: contar a los tuyos cada noche y no dormir hasta que salieran las cuentas."),
        Linea(flag: "SENDA_DEL_CAZADOR",
              texto: "Elegiste la senda del Cazador: llegar antes que el problema, siempre."),
        Linea(flag: "SENDA_DEL_DIPLOMATICO",
              texto: "Elegiste la senda del Diplomático: ganar las habitaciones antes que los campos de batalla."),
        Linea(flag: "SENDA_DEL_INFILTRADO",
              texto: "Elegiste la senda del Infiltrado: estar donde nadie te había invitado y salir sin que se notara."),
        Linea(flag: "SENDA_DEL_INDEPENDIENTE",
              texto: "Elegiste la senda del Independiente: no deberle nada a nadie, y pagar el precio de no tener a quién pedírselo."),
        Linea(flag: "SENDA_DEL_PEREGRINO",
              texto: "Elegiste la senda del Peregrino: andar hacia la Cadena como quien va a rezar, no como quien va a romperla."),
        Linea(flag: "SENDA_DE_LA_EMISARIA",
              texto: "Elegiste la senda de la Emisaria: hablar por los que no tenían con qué hablar."),
        Linea(flag: "SENDA_DE_LA_HEREJE",
              texto: "Elegiste la senda de la Hereje: hacer la pregunta que estaba prohibida y no bajar la voz al hacerla."),
        Linea(flag: "CAMINO_EN_SOLITARIO",
              texto: "Hiciste casi todo el camino en solitario. No fue orgullo: fue que soltar a la gente te parecía más limpio que enterrarla."),
        Linea(flag: "GRUPO_UNIDO",
              texto: "El grupo llegó entero hasta donde pudo llegar un grupo. Eso, en estos años, es casi un milagro administrativo."),
        Linea(flag: "NO_VAS_SOLA",
              texto: "Alguien te dijo, en el peor momento, que no ibas por tu cuenta. Resultó ser verdad."),
        Linea(flag: "ALIADA_NIMA",
              texto: "Nima sigue viva y sigue siendo insoportable. Te manda cartas que no contestas y que guardas todas."),
        Linea(flag: "TREGUA_DE_LA_ESTEPA",
              texto: "La tregua de la estepa aguantó más que muchos tratados firmados con lacre. Nadie la escribió nunca."),
        Linea(flag: "CLANES_DE_LA_ESTEPA",
              texto: "Los clanes de la estepa te cuentan entre las pocas personas del sur que dijeron lo que iba a hacer y luego lo hizo."),
        Linea(flag: "ORDEN_DIVIDIDA_CONOCIDA",
              texto: "Supiste antes que la propia Orden que la Orden estaba partida en dos. Tardaron años en admitir en voz alta lo que tú viste en una tarde."),
        Linea(flag: "LISTA_DEL_CENSO",
              texto: "La lista del Censo acabó copiada, repartida y leída en sitios donde no debía leerse. Ya no hay forma de volver a esconder esos nombres."),
        Linea(flag: "CIEN_NOMBRES",
              texto: "Cien nombres. Los leíste todos en voz alta porque alguien tenía que hacerlo, y porque leerlos deprisa habría sido otra forma de perderlos."),
        Linea(flag: "LISTA_DE_NOMBRES",
              texto: "Guardaste la lista de nombres hasta el final. No servía para nada. Servía para no olvidar para qué habías ido."),
        Linea(flag: "VERDAD_ANTE_LAS_CASAS",
              texto: "Dijiste la verdad delante de las Cinco Casas, en su salón, con sus guardias en la puerta. No te lo han perdonado y no hacía falta que lo hicieran."),
        Linea(flag: "REPUTACION_EN_LOS_MUELLES",
              texto: "En los muelles de Cárdenas tu nombre todavía abre puertas y cierra conversaciones, según quién esté escuchando."),
        Linea(flag: "CONTACTO_CON_SERA",
              texto: "Sera nunca te dio las gracias. Te dio algo mejor: siguió pasándote información cuando ya no tenía ningún motivo para hacerlo."),
        Linea(flag: "CONTACTO_CON_VAAS",
              texto: "Vaas cumplió su parte. Cobrarla le costó más de lo que había calculado, y aun así la cumplió."),
        Linea(flag: "DENNA_ESCUCHADA",
              texto: "Escuchaste a Denna hasta el final, sin interrumpirla. Fue la primera persona que lo hizo en once años."),
        Linea(flag: "VERDAD_DEL_LIGAMEN",
              texto: "Aprendiste qué es de verdad un Ligamen. Hay conocimientos que no se pueden devolver."),
        Linea(flag: "DOCE_VOLUNTARIOS",
              texto: "Fueron doce los que levantaron la mano sabiendo lo que había abajo. Sus nombres están en el diario de la Cuarta, con la letra apretada del final."),
        Linea(flag: "VOLUNTARIOS_DEL_VALLE",
              texto: "La gente del valle se ofreció sin que nadie se lo pidiera. Es lo que más te costó aceptar de todo el viaje."),
        Linea(flag: "MARCADOS_CONSULTADOS",
              texto: "Preguntaste a los Marcados antes de decidir por ellos. Parece poca cosa. En trescientos años nadie lo había hecho."),
        Linea(flag: "MARCADOS_DEL_VALLE",
              texto: "Los Marcados del valle dejaron de esconder la muñeca. No todos, no en todas partes, pero empezaron."),
        Linea(flag: "LA_COLUMNA_CRUZO",
              texto: "La columna cruzó. Tardó tres días más de lo previsto y llegó entera, que era lo único que importaba."),
        Linea(flag: "EXPEDICION_UNIDA",
              texto: "La expedición no se rompió por dentro, que era la forma en que se rompían todas las anteriores."),
        Linea(flag: "CANCION_VARDA",
              texto: "Alguien silbó la canción varda en el descenso, donde no debía sonar nada. Aquello os sostuvo más que las cuerdas."),
        Linea(flag: "ILENA_ALIADA",
              texto: "Ilena dejó de vigilarte en algún punto del camino y empezó a caminar a tu lado. Nunca comentasteis el cambio."),
        Linea(flag: "CONDICIONES_A_ILENA",
              texto: "Le pusiste condiciones a Ilena y las aceptó. Las cumplió incluso cuando dejaste de estar en posición de exigirlas."),
        Linea(flag: "DIARIO_DE_LA_CUARTA",
              texto: "El diario de la Cuarta Expedición volvió a la superficie contigo. Se lee mal, se entiende peor y es el documento más honesto que existe sobre la Grieta."),
        Linea(flag: "CUARTA_OPCION_PLANTEADA",
              texto: "Plantéaste una cuarta salida cuando todo el mundo daba por hechas que solo había tres. Que funcionara o no es otra discusión: la planteaste."),
        Linea(flag: "SEGUNDA_RESPONDIDA",
              texto: "Respondiste a la segunda pregunta. La primera la responde cualquiera; la segunda solo se responde sabiendo lo que cuesta."),
        Linea(flag: "ASHKELEN_NOMBRADO",
              texto: "Nombraste a Ashkelen en voz alta. Los nombres, abajo, no son una formalidad."),
        Linea(flag: "RASTRO_DE_ASHKELEN",
              texto: "Seguiste el rastro de Ashkelen hasta donde el rastro dejaba de ser un rastro y pasaba a ser una invitación."),
        Linea(flag: "POSTURA_REFORJAR",
              texto: "Bajaste convencida de que la Cadena podía reforjarse. Lo que viste abajo no te hizo cambiar de idea, y eso también hay que sostenerlo."),
        Linea(flag: "POSTURA_ROMPER",
              texto: "Bajaste convencida de que la Cadena tenía que romperse. Nadie que estuviera allí puede decir que no te avisaron."),
        Linea(flag: "POSTURA_PREGUNTAR",
              texto: "Bajaste sin decidir nada, dispuesta a preguntar primero. Fue la postura menos heroica y la única que dejó sitio a lo que encontraste."),
        Linea(flag: "MAPA_DE_LAS_FAUCES",
              texto: "El mapa de las Fauces sigue doblado en cuatro, con tus correcciones al margen. Alguien lo usará después de ti y le salvará la vida sin saber a quién."),
        Linea(flag: "TABLILLA_DE_ARCILLA_RUNICA",
              texto: "La tablilla rúnica está en manos de gente que sabe leerla. Discuten sobre ella. Discutir sobre ella ya es mejor que lo que había antes."),
        Linea(flag: "LAS_FAUCES_ROTAS",
              texto: "Las Fauces quedaron rotas a tu paso. La ruta del norte volvió a ser una ruta y no una emboscada con nombre propio."),
        Linea(flag: "RECONOCIDO_POR_LA_ORDEN",
              texto: "La Orden de la Ceniza acabó reconociéndote. Tarde, a regañadientes y por escrito, que es como reconoce la Orden."),
        Linea(flag: "AGENTE_DE_LA_ORDEN",
              texto: "Trabajaste para la Orden. Cargar con eso resultó ser más complicado que cargar con la Marca."),
        Linea(flag: "ALIADA_INDEPENDIENTE_DE_LA_ORDEN",
              texto: "Ayudaste a la Orden sin pertenecer a ella. Nunca supieron dónde ponerte, y esa fue exactamente tu ventaja."),
        Linea(flag: "PACTO_CON_SERA",
              texto: "Le prometiste a Sera que la avisarías antes de usar la lista, y la avisaste. En El Refugio aún se cuenta que hubo tiempo de sacar a la gente porque alguien de fuera cumplió su palabra."),
        Linea(flag: "EVIDENCIA_SIN_ATADURAS",
              texto: "No le prometiste a Sera lo que no pensabas cumplir. Usaste la lista cuando hizo falta, sin permiso de nadie. Salvó la votación; no salvó a todo el mundo."),
        Linea(flag: "REFUGIO_PROTEGIDO",
              texto: "El Refugio nunca salió de tu boca. Sigue sin aparecer en ningún registro, ningún informe y ninguna crónica oficial: existe porque tú no lo nombraste."),
        Linea(flag: "REFUGIO_COMO_BAZA",
              texto: "Te reservaste el derecho de enseñar El Refugio si hacía falta, y Sera te dejó marchar sabiéndolo. Esa honestidad incómoda es lo único que le impidió sentirse traicionada después."),
        Linea(flag: "ENCARGO_SIN_PREGUNTAS",
              texto: "Aceptaste el encargo de Casa Vaas sin preguntar de qué se trataba. Corvina lo contó durante años como la prueba de que se podía confiar en ti; nunca supo lo cerca que estuvo de costarte la vida."),
        Linea(flag: "ENCARGO_CON_CONDICIONES",
              texto: "Antes de trabajar para Casa Vaas exigiste saber en qué te metías. Corvina no estaba acostumbrada a que le preguntaran, y acabó tratando contigo de igual a igual por eso."),
        Linea(flag: "NOCHE_DE_BALANCE",
              texto: "Pasaste tu última noche libre caminando en solitario por Cárdenas, poniendo en orden lo que sabías. Entraste en el palacio sin haber dormido y sin una sola duda."),
        Linea(flag: "NOCHE_EN_VELA",
              texto: "No pegaste ojo la víspera de la Convocatoria. Las piezas sueltas te tuvieron despierta hasta el amanecer, y por eso las tenías todas a mano cuando hizo falta."),
        Linea(flag: "ULTIMO_CONSEJO_DE_CORVINA",
              texto: "Esperaste despierta y Corvina apareció, como sospechabas. «No dejes que decidan por ti cuál de las dos eres.» Fue lo último que te dijo, y lo único que recordaste dentro del palacio."),
        Linea(flag: "ENTRADA_ANUNCIADA",
              texto: "Entraste en el monasterio por la puerta principal, a plena luz y con el salvoconducto por delante. Nadie pudo decir nunca que te hubieras colado; todos supieron desde el primer minuto que estabas allí."),
        Linea(flag: "ALA_ESTE_VISTA_DE_CERCA",
              texto: "Rodeaste el monasterio antes de anunciarte y viste el ala este por tu cuenta: los andamios que no reparaban nada, la piedra vidriada, el camino de carro que bajaba desde la portezuela de servicio. Supiste que estaban vaciando aquel sitio mucho antes de que nadie te lo contara."),
        Linea(flag: "HERIDA_DE_VALCENAR",
              texto: "La herida de la primera noche en Valcenar no se cerró nunca del todo. Cambia de color con el frío y te recuerda, sin dramatismo, que estuviste a punto de no pasar de la primera calle."),
        Linea(flag: "HERIDA_DEL_CAMPAMENTO",
              texto: "Cael te sacó de una pelea que ya habías perdido y no volvió a mencionarlo jamás. Tú tampoco, pero desde entonces miras las manos y no la cara."),
        Linea(flag: "PRECIO_PAGADO",
              texto: "Un hombre flaco que apenas habló en toda la marcha recibió en tu lugar lo que iba dirigido a ti. Vive. No anda igual. Sabes su nombre y nunca lo dices en voz alta."),
        Linea(flag: "NOCHE_DIFICIL",
              texto: "Hubo una noche de cuervos y cristal en que alguien a tu cargo acabó con un corte que no debería haber tenido. Nadie te lo reprochó, y por eso te duró más."),
        Linea(flag: "MAREADO_POR_LA_GRIETA",
              texto: "La primera vez que la Grieta te habló de cerca perdiste el rastro y el equilibrio. Nunca volviste a acercarte a una sin contar antes tus propios pasos."),
        Linea(flag: "RETIRADA_FORZOSA",
              texto: "Corriste. En los relatos que se cuentan de ti nadie menciona esa noche, porque no la contaste tú: fue la que te enseñó a contar enemigos antes de desenvainar."),
        Linea(flag: "ATAQUE_PREMATURO",
              texto: "Ganaste aquella pelea y despertaste a un campamento entero. Desde entonces mides el ruido de todo lo que haces, incluso de lo que sale bien."),
        Linea(flag: "HUECO_CONOCIDO",
              texto: "Memorizaste el hueco exacto de una ronda de guardia y entraste por él. Es una habilidad discreta que no impresiona a nadie y que te salvó más de una vez."),
        Linea(flag: "COSTE_DEL_SENUELO",
              texto: "Nunca supiste si el prisionero que hizo de señuelo llegó a salir de allí. Aprendiste a no preguntar por él, que es otra manera de no olvidarlo."),
        Linea(flag: "RUIDO_EN_LA_PRISION",
              texto: "El metal contra el metal se oyó por todo el corredor y aun así saliste con la gente de las celdas. Hay quien lo cuenta como audacia; tú sabes que fue suerte."),
        Linea(flag: "SABOTAJE_LOGRADO",
              texto: "Rompiste el soporte del altar a golpes, delante de todos, y el vórtice tembló. Fue tosco, ruidoso y exactamente lo que hacía falta."),
        Linea(flag: "SABOTAJE_FALLIDO",
              texto: "Golpeaste el soporte, no rompiste nada y la cámara entera supo que estabas dentro. Pagaste el precio del intento sin llegar a cobrar la recompensa."),
        Linea(flag: "MARCADOS_LIBERADOS",
              texto: "Los Marcados encadenados en el sótano salieron por su propio pie. Algunos siguen sin saber quién abrió las argollas; los otros no han dejado de contarlo."),
        Linea(flag: "BASTIAN_LIBERADO",
              texto: "Bastian volvió a ser un hombre en el peor sitio posible, y lo primero que hizo con las manos recuperadas fue soltar a otros. Eso lo decidiste tú."),
        Linea(flag: "PARTIDA_INMEDIATA",
              texto: "Partiste el mismo día, sin despedirte de nadie. Ganaste una jornada y dejaste atrás conversaciones que ya no se pudieron tener."),
        Linea(flag: "DESPEDIDA_CONSCIENTE",
              texto: "Te tomaste un día entero para despedirte antes de partir. Fue tiempo perdido en todos los informes y la única despedida que llegaste a tener."),
        Linea(flag: "APOYO_A_ORWYN",
              texto: "Apoyaste a Orwyn en voz alta cuando apoyarlo todavía costaba algo. Él no lo ha olvidado, y en la Orden hay quien tampoco."),
        Linea(flag: "RESERVA_DIPLOMATICA",
              texto: "No dijiste de qué lado estabas hasta haber escuchado a las dos partes. Te dio fama de cautela y te ahorró dos enemigos que no necesitabas."),
        Linea(flag: "COMPROMISO_ABIERTO_VAAS",
              texto: "Te comprometiste con Casa Vaas delante de testigos. Meritxell cumplió su parte; en Cárdenas aún se discute si tú saliste ganando."),
        Linea(flag: "GUARDIAN_DEL_CENSO_DERROTADO",
              texto: "El Guardián del Censo cayó, y la maquinaria que protegía quedó a la vista de cualquiera. Nadie ha vuelto a levantarla igual."),
        Linea(flag: "VOLUNTARIOS_RECHAZADOS",
              texto: "Rechazaste el sacrificio de los treinta y siete y exigiste una solución que no costara vidas. Unos te lo agradecieron; otros te acusaron de retrasar lo inevitable."),
        Linea(flag: "PACTO_PROPUESTO",
              texto: "Le propusiste un pacto a algo que llevaba ochocientos años sin que nadie le propusiera nada. Salga como salga, ya no puede decirse que no se intentó."),
        Linea(flag: "DECISION_REFORJAR",
              texto: "Elegiste reforjar la cadena. Vaelgard sigue en pie sobre esa decisión, con todo lo que arrastra."),
        Linea(flag: "DECISION_ROMPER",
              texto: "Elegiste romper la cadena. Lo que vino después no lo decidiste tú, pero lleva tu nombre igualmente."),
        Linea(flag: "DECISION_ATACAR",
              texto: "Elegiste atacar. Nadie que estuviera allí abajo discute que hacía falta valor; unos cuantos siguen discutiendo si hacía falta."),
        Linea(flag: "PALABRAS_DEL_PADRE_CENIZA",
              texto: "Te quedaste a escuchar al Padre Ceniza cuando podías haberte marchado. Repites sus palabras de vez en cuando, y cada año te suenan de otra manera."),
        Linea(flag: "BREN_RESCATADO",
              texto: "Sacaste a Bren de las Fauces Rotas. Aprendió un oficio, se quedó en un pueblo pequeño y sigue mandando mensajes de tres palabras cada pocas semanas."),
        Linea(flag: "NINOS_A_SALVO",
              texto: "Los niños que sacaste del Confín crecieron. Tres de ellos no tenían a nadie, y ahora cuentan tu historia a los recién llegados con bastantes más dragones de los que hubo."),
        Linea(flag: "TOMAS_VACILA",
              texto: "Tomás dudó delante de ti, y esa duda le costó la Secta. Nadie sabe dónde acabó; tú esperas que en algún sitio donde no le pregunten."),
        Linea(flag: "SEREL_INTERPELADA",
              texto: "Obligaste a Serel Ashvane a decir en voz alta lo que la Orden prefería callar. Le costó el mando y no te lo ha reprochado nunca."),
        Linea(flag: "SEREL_RESPETADA",
              texto: "No presionaste a Serel Ashvane cuando podías haberlo hecho. Años después, cuando necesitaste que alguien de la Orden respondiera por ti, respondió ella."),
        Linea(flag: "ALIANZA_REFUGIO",
              texto: "Ataste tu suerte a El Refugio. Dejó de ser un escondite y empezó a ser un sitio, que es una diferencia que solo entienden los que han vivido en los dos."),
        Linea(flag: "ALIANZA_VAAS",
              texto: "Te aliaste con Casa Vaas. Fue útil, fue caro, y ninguna de las dos cosas se puede discutir."),
        Linea(flag: "ORDAZ_EXPUESTA",
              texto: "Pusiste a Elliana Ordaz delante de sus propios papeles. El Consejo tardó años en recuperarse de aquella sesión, y en algunos sentidos no se recuperó."),
        Linea(flag: "MANO_DURA",
              texto: "Elegiste la mano dura cuando había otra salida. Funcionó. Es exactamente eso lo que te sigue quitando el sueño."),
        Linea(flag: "MISERICORDIA",
              texto: "Tuviste misericordia con quien no la esperaba. Te ha salido cara alguna vez, y aún así volverías a hacerlo."),
        Linea(flag: "VERDAD_COMPARTIDA",
              texto: "Contaste la verdad entera cuando podías haberte guardado la mitad. Media Vaelgard te lo agradece; la otra media te tiene fichada por ello."),
        Linea(flag: "REFUGIADOS_A_SALVO_EN_MARREN",
              texto: "La gente que llevaste hasta Marren sigue en Marren. Levantaron casas, discuten por lindes y se han olvidado casi del todo de cómo llegaron. Ese olvido es tu obra."),
        Linea(flag: "RITUAL_INVESTIGADO",
              texto: "Investigaste el ritual en vez de conformarte con lo que te contaban. Lo que averiguaste no te hizo más feliz, pero sí más difícil de engañar."),
        Linea(flag: "EL_PRECIO_REAL_DEL_RITUAL",
              texto: "Averiguaste lo que costaba de verdad el ritual, y lo supiste antes que casi nadie. Cargar con esa información a solas fue su propio castigo."),
        Linea(flag: "CADENA_COMPRENDIDA",
              texto: "Llegaste al fondo entendiendo la cadena, no solo temiéndola. Muy poca gente en ochocientos años puede decir lo mismo."),
        Linea(flag: "NOMBRE_DE_CORVO",
              texto: "Le devolviste su nombre a Corvo Ashkelen. Llevaba ocho siglos siendo un ancla; volvió a ser, aunque fuera un momento, el hijo menor de alguien."),
        Linea(flag: "CORVO_EN_PAZ",
              texto: "Corvo subió contigo. Vio un techo distinto por primera vez en ochocientos años y se pasó la primera noche entera mirando al cielo sin decir nada."),
        Linea(flag: "ILENA_EN_PAZ",
              texto: "Ilena Fos encontró su paz, y fue contigo delante. No te dio las gracias —no era de esas—, pero te dejó quedarte."),
        Linea(flag: "ILENA_VA_POR_DELANTE",
              texto: "Ilena Fos llegó antes que tú a todas partes. Aún discutes contigo si te estaba abriendo camino o cerrándotelo."),
        Linea(flag: "ASHKELEN_TE_CONOCE",
              texto: "Ashkelen aprendió tu nombre. Hay una diferencia enorme entre soñar con algo y que ese algo sueñe contigo, y tú la conociste por dentro."),
        Linea(flag: "DUELO_POR_ASHKELEN",
              texto: "Te dolió su muerte, y ese duelo no se lo has confesado a nadie, porque no hay forma de explicarlo sin que suene a traición."),
        Linea(flag: "ASHKELEN_MUERTO",
              texto: "Mataste a Ashkelen. Las Grietas se cerraron todas y la Marca se apagó para todos los que la llevaban. Ambas frases son verdad y tú tienes que vivir con las dos."),
        Linea(flag: "PACTO_ACEPTADO",
              texto: "El pacto se cerró. Nadie tiene un nombre para lo que sois ahora tú y lo que hay bajo el Confín, y probablemente sea mejor así."),
        Linea(flag: "COLGANTE_DE_LA_CADENA_ROTA",
              texto: "Conservas un eslábon de la cadena colgado al cuello. Pesa mucho más de lo que debería pesar un trozo de metal de ese tamaño."),
    ]

    private static let indice: [String: String] = Dictionary(uniqueKeysWithValues: lineas.map { ($0.flag, $0.texto) })

    /// Las líneas de epílogo ganadas, en orden de lectura.
    static func para(_ flags: Set<String>, maximo: Int = maximoDeLineas) -> [String] {
        var resultado: [String] = []
        for linea in lineas where flags.contains(linea.flag) {
            resultado.append(linea.texto)
            if resultado.count >= maximo { break }
        }
        return resultado
    }

    static func linea(para flag: String) -> String? { indice[flag] }
}
